# Konfigurationsdatei für das Release-Drafter-Tool.
# release-drafter-config.yml

# Definiert die Vorlage für den Namen des Releases.
name-template: 'v$RESOLVED_VERSION' # Automatisch erhöhte Versionsnummer

# Definiert die Vorlage für den Namen des Release-Tags.
tag-template: 'v$RESOLVED_VERSION' # Automatisch erhöhte Versionsnummer

# Kategorien für das Changelog, identifiziert durch Labels auf Pull Requests.
categories:
  - title: 'Features'
    labels:
      - 'enhancement'
  - title: 'Bug Fixes'
    labels:
      - 'bug'
  - title: 'Dokumentation'
    labels:
      - 'documentation'

# Layout des Changelogs, formatiert nach den Änderungen in den Pull Requests.
template: |
  ## Änderungen
  $CHANGES

# Vorlage für jede Änderung (Pull Request), einschließlich Beschreibung.
change-template: |
  ### $TITLE (@$AUTHOR) [#$NUMBER]
  
  $BODY

# PRs mit diesen Labels aus den Release Notes ausschließen
exclude-labels:
  - 'ignore-in-release-notes'

# Version-Resolver bestimmt die Art der Versionserhöhung basierend auf den PR Labels.
version-resolver:
  major:
    labels:
      - 'breaking'
  minor:
    labels:
      - 'enhancement'
  patch:
    labels:
      - 'bug'
      - 'documentation'
  default: patch
