name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'

categories:
  - title: 'Features'
    labels:
      - 'feature'
      - 'enhancement'
  - title: 'Bug Fixes'
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'
  - title: 'Maintenance'
    label: 'chore'

# Vorlage für jede Änderung (Pull Request), inklusive Titel, Autor und Body (PR Beschreibung).
change-template: |
  ### $TITLE (@$AUTHOR) [#$NUMBER]

  $BODY

# Definiert die Zeichen, die in den Titeln korrekt escaped werden sollen.
change-title-escapes: '\<*_&' 

# Version-Resolver, der die Art der Versionserhöhung basierend auf Labels festlegt.
version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'minor'
  patch:
    labels:
      - 'patch'
  default: patch

# Vorlage für das gesamte Release-Template, mit allen PR-Änderungen.
template: |
  ## Changes

  $CHANGES
