[tool.poetry]
name = "kurmann-videoschnitt"
authors = ["Patrick Kurmann <kurmannwillisau@gmail.com>"]
version = "0.46.2"
description = "Sammlung von Werkzeugen zur Automatisierungen im privaten Videoschnitt"
readme = "README.md"
license = "Apache-2.0"

[tool.poetry.dependencies]
python = ">=3.8,<4.0"
click = "^8.1.7"
python-dotenv = "^1.0.1"

[tool.setuptools.packages.find]
where = ["src"]

[tool.poetry.scripts]
kurmann-videoschnitt = "kurmann_videoschnitt.cli:cli"
apple-compressor-manager = "apple_compressor_manager.cli:cli"
emby-integrator = "emby_integrator.cli:cli"