[tool.poetry]
name = "kurmann-videoschnitt"
authors = ["Patrick Kurmann <kurmannwillisau@gmail.com>"]
version = "0.51.0"
description = "Sammlung von Werkzeugen zur Automatisierungen im privaten Videoschnitt"
readme = "README.md"
license = "Apache-2.0"

[tool.poetry.dependencies]
python = ">=3.8,<4.0"
click = "^8.1.7"
python-dotenv = "^1.0.1"
typer = "^0.12.5"
osxmetadata = {version = "^1.3.5", python = ">=3.8,<3.13"}

[tool.setuptools.packages.find]
where = ["src"]

[tool.poetry.scripts]
kurmann-videoschnitt = "kurmann_videoschnitt.app:app"