name: Release Drafter

on:
  push:
    # Nur für den "master" (oder "main") Branch, auf dem der Release-Draft erstellt werden soll
    branches:
      - master
  pull_request:
    # Diese Events werden benötigt, wenn du die Autolabeler-Funktion nutzt
    types: [opened, reopened, synchronize]

permissions:
  contents: read

jobs:
  update_release_draft:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      
      # Führe Tests nur aus, wenn ein Node.js-Projekt vorhanden ist
      # - run: npm test

      - uses: release-drafter/release-drafter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
