name: Test, Build, and Release

on:
  release:
    types:
      - created
  workflow_dispatch:

jobs:
  release:
    runs-on: macos-latest

    env:
      CSPROJ_FILE: src/Application/Application.csproj
      DOTNET_VERSION: '9.0.x'

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Install dependencies
        run: dotnet restore ${{ env.CSPROJ_FILE }}

      - name: Build
        run: dotnet build --configuration Release --no-restore ${{ env.CSPROJ_FILE }}

      - name: Test
        run: dotnet test ${{ env.CSPROJ_FILE }}

      - name: Publish for Apple Silicon
        run: dotnet publish --configuration Release --self-contained -r osx-arm64 --output ./publish ${{ env.CSPROJ_FILE }}

      - name: Archive files
        run: tar -czvf Kurmann.Videoschnitt-macos-arm64.tar.gz -C ./publish .

      - name: Upload Release Asset
        uses: shogo82148/actions-upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: Kurmann.Videoschnitt-macos-arm64.tar.gz